### ISSUE TITLE
Kubernates (K8s) Image Pull Secrets

### ISSUE THREAD

**Issue by TuncerKARAARSLAN-VB** [rifaterdemsahin/rancherdesktoponwindows#5]
### Adım 1: Lokal Docker Registry'yi Kurun
Eğer lokal Docker registry'niz yoksa, aşağıdaki komutla bir tane başlatabilirsiniz:

```bash
docker run -d -p 5000:5000 --restart=always --name registry registry:2
```

Bu komut, Docker'ın yerel registry servisini `localhost:5000` adresinde çalıştıracaktır.

### Adım 2: Docker Registry'ye İmaj Push Etme
Lokal registry'nize bir imajı göndermek için, imajı etiketleyip `localhost:5000` ile push edebilirsiniz.

1. Docker imajını yeniden etiketleyin:
   ```bash
   docker tag your-image-name localhost:5000/your-image-name
   ```

2. İmajı lokal registry'ye push edin:
   ```bash
   docker push localhost:5000/your-image-name
   ```

Bu işlemden sonra imajınız lokal registry'de yer alacaktır.

### Adım 3: Kubernetes'te Docker Registry Secret Oluşturma
Lokal registry'ye erişmek için bir Kubernetes secret oluşturmanız gerekecek. Aşağıdaki komutla secret oluşturun:

```bash
kubectl create secret docker-registry my-local-registry-secret \
  --docker-server=http://localhost:5000 \
  --docker-username=<your-username> \
  --docker-password=<your-password> \
  --docker-email=<your-email>
```

Eğer lokal registry için kimlik doğrulama (username/password) gerekmiyorsa, bu adımı atlayabilirsiniz.

### Adım 4: YAML Dosyanıza `imagePullSecrets` Ekleyin
Kubernetes pod’unuzda yerel Docker registry imajını kullanmak için `imagePullSecrets` kısmını YAML dosyanıza ekleyin. Ayrıca, imaj adında yerel registry'nin adresini kullanmalısınız.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  namespace: hello-world
spec:
  containers:
  - name: hello-world
    image: localhost:5000/your-image-name
    ports:
    - containerPort: 8080
  imagePullSecrets:
  - name: my-local-registry-secret
```

Eğer Docker registry kimlik doğrulaması gerekmiyorsa `imagePullSecrets` kısmını eklemenize gerek yoktur.

### Adım 5: Pod'u Uygulama
Bu adımlardan sonra pod'u oluşturmak için aşağıdaki komutu kullanabilirsiniz:

```bash
kubectl apply -f hello-world-pod.yaml
```

Bu adımları izledikten sonra lokal Docker registry'nizden Kubernetes'e imaj çekebilir ve uygulamanızı deploy edebilirsiniz.
